run_name: unetr_inf128_lr
batch_size: 4
optim_lr: 5e-5
device: cuda:0

log_dir: 'logs/${run_name}'
val_every: 20
save_every: 40
inf_size: 128
in_channels: 1
modality: [0]
out_channels: 14
feature_size: 16
hidden_size: 768
mlp_dim: 3072
num_heads: 12
pos_embed: perceptron
norm_name: instance
dropout_rate: 0.0
pretrained: false
path_to_pretrain: null
path_to_checkpoint: null
smooth_nr: 0.
smooth_dr: 1e-6
sw_batch_size: 1
infer_overlap: 0.5
optim_name: adamw
optim_weight_decay: 1e-5
momentum: 0.99
lrschedule_name: warmup_linear
warmup_epochs: 10
max_epochs: 100000
data_dir: ~/dev/data/msd/
json_name: dataset.json
spacing: [1., 1., 1.]
a_min: 175.
a_max: 250.
b_min: 0.
b_max: 1.
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
n_workers: 10
cache_num: 20
